#!/bin/bash

# SPDX-FileCopyrightText: 2016-2020 Graham R. Cobb
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2016 Graham R. Cobb
# Released under GPL V3.0 -- see LICENSE
#
# extents-union [-s] <filename>...
#
#
# Output the extents contained in any of the named extents lists
#

if [ "$1" = "-s" ]
then
    shift
    $0 "$@" | extents-size
    exit $?
fi

if [ $# -eq 0 ]
then
    echo "$0: No file specified" >&2
    echo "Usage: $0 <filename>..." >&2
    exit 1
fi

cat "$@" | extents-merge
