#!/bin/bash

# SPDX-FileCopyrightText: 2016-2020 Graham R. Cobb
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2016 Graham R. Cobb
# Released under GPL V3.0 -- see LICENSE
#
# extents-size [<blocksize>]
#
# Blocksize defaults to 4096
#

blocksize=4096
[ -n "$1" ] && blocksize=$1

blocks=0

while read start end restofline && [ -n "$start" ] ; do let blocks+=(end-start+1) ; done

let size=blocks*blocksize
let gb=size/1024/1024/1024

echo "$blocks blocks = $size bytes (${gb}GB)"

